// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kddofxcnymiycaabuhga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkZG9meGNueW1peWNhYWJ1aGdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDA0MjUsImV4cCI6MjA1ODExNjQyNX0.pqDE65JNUqcA0iy3eepitQyLIpLsoTLKI17iIUbDOPY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);